### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by isisAnchalee** [isisAnchalee/letspair#1]
TODO:
- [x] signup form
- [x] sign in form
- [x] sessions_controller
- [x] devise auth

Instances of User:
- [x] Admin
- [x] End-User
- [ ] Expert

**Comment by Dbz** [comment]
Do we want End User and expert to be different?

**Comment by Dbz** [comment]
We actually might want experts to be specially invited through a sign up or something/application

**Comment by Dbz** [comment]
I will look into the benefits of creating different models for admin and expert, but for now I just have a flag for admin and may add a flag for expert.

**Comment by Dbz** [comment]
No longer relevant
